/* Generated by Opal 0.6.2 */
(function($opal) {
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice;

  $opal.add_stubs(['$puts']);
  self.$puts("Hello, world!");
  return self.$puts("Running Shoes " + (($scope.Shoes)._scope.VERSION));
})(Opal);
